# Generated by Django 2.2.6 on 2019-11-11 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newfood',
            name='entry_id',
        ),
    ]
