# Generated by Django 2.2.6 on 2019-11-11 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpjct', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofileinfo',
            options={'verbose_name_plural': 'userprofiles'},
        ),
    ]
